app/component/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import *
from wtforms.validators import DataRequired, Length


# 定义表单类
class ComponentForm(FlaskForm):
    name = StringField(u'名称', validators=[DataRequired(u"必填项"), Length(1, 20)], description=u"名称")
    type = SelectField(u'类型',
                       choices=[('install', u'安装'), ('upgrade', u'升级'),
                                ('optimize', u'优化'), ('uninstall', u'卸载')
                                ],
                       validators=[DataRequired(u"必填项")]
                       )
    version = StringField(u'版本', validators=[DataRequired(u"必填项"), Length(1, 20)])
    os = StringField(u'适用于(系统)', validators=[DataRequired(u"必填项"), Length(1, 20)])
    content = TextAreaField(u'脚本', validators=[DataRequired(u"必填项")])
    files = FileField(u'安装包/脚本上传')
    templates = FileField(u'配置/模版上传')
    notes = TextAreaField(u'备注', validators=[Length(max=200)])
    # submit = SubmitField(u'提交')

app/component/__init__.py
from flask import Blueprint

component = Blueprint('component', __name__)

from . import views

app/component/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import render_template, request, session, flash, redirect, url_for, current_app
from flask_login import login_required
import json
import os
from werkzeug.utils import secure_filename

# from ..base import _render
from . import component
from forms import ComponentForm
from ..models import Component, UploadFile, Variable
from .. import db


@component.route('/index', methods=['GET'])
@login_required
def index():
    header = u'管理'
    objects = Component.query.all()
    return _render('index', locals())

# 显示变量列表
@component.route('/variable_index/<int:id>', methods=['GET'])
@login_required
def variable_index(id):
    title_name = u'变量'
    header = u'管理'
    component = Component.query.get_or_404(id)
    objects = component.variables.all()
    return _render('variable_index', locals())

# 显示文件列表
@component.route('/file_index/<int:id>', methods=['GET'])
@login_required
def file_index(id):
    title_name = u'文件'
    header = u'管理'
    component = Component.query.get_or_404(id)
    objects = component.upload_files.all()
    return _render('file_index', locals())


@component.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    header = u'添加'
    form = ComponentForm()
    if request.method == "POST":
        if form.validate_on_submit():
            # 保存组件信息
            component = Component(name=form.name.data,
                                  type=form.type.data,
                                  version=form.version.data,
                                  os=form.os.data,
                                  content=form.content.data,
                                  notes=form.notes.data)
            db.session.add(component)
            db.session.flush()

            # 保存变量
            save_variable(request, component)

            # 保存上传的文件
            files = request.files.getlist("files[]")
            templates = request.files.getlist("templates[]")

            # 轮询上传过来的文件保存到指定文件夹及数据库
            for file in files:
                save_upload_file(file, 'file', component)

            for file in templates:
                save_upload_file(file, 'template', component)

            # 将组件及上传文件信息提交到数据库
            db.session.commit()

            flash(u'组件{}添加成功!'.format(component.name))
            return redirect(url_for('.index'))

        else:
            flash(u'表单校验未通过,添加失败!', 'danger')

    return _render('form', locals())


@component.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    header = u"编辑"
    obj = Component.query.get_or_404(id)
    form = ComponentForm(obj=obj)
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(obj)
            # 保存变量
            save_variable(request, obj)

            # 保存上传的文件
            files = request.files.getlist("files[]")
            templates = request.files.getlist("templates[]")

            # 轮询上传过来的文件保存到指定文件夹及数据库
            for file in files:
                filename = secure_filename(file.filename)
                save_upload_file(file, 'type', obj)

            for file in templates:
                save_upload_file(file, 'type', obj)

            # 将组件及上传文件信息提交到数据库
            db.session.commit()
            flash(u'组件{}编辑成功!'.format(obj.name))
            return redirect(url_for(".index"))
        else:
            flash(u'表单校验未通过,编辑失败!', 'danger')
    return _render('form', locals())


@component.route('/delete/<int:id>', methods=['GET'])
@login_required
def delete(id):
    obj = Component.query.get(id)
    db.session.delete(obj)
    db.session.commit()
    flash(u'数据删除成功!')
    return redirect(url_for('.index'))


# ajax方式动态增加组件变量
@component.route('/ajax_add_var_tr/<int:i>', methods=['GET', 'POST'])
@login_required
def ajax_add_var_tr(i):
    return _render('_var_tr', locals())


# 保存变量
def save_variable(request, component):
    var_names = request.form.getlist("var_name[]")
    var_values = request.form.getlist("var_value[]")
    counter = 0
    for var in var_names:
        counter += 1
        if not var:
            continue
        value = var_values[counter - 1]
        type = request.form['var_type_%s' % counter]
        variable = Variable(name=var, value=value, type=type, component_id=component.id)
        db.session.add(variable)


# 保存上传文件
def save_upload_file(file, type, component):
    if file:
        upload_path = current_app.config['UPLOAD_FOLDER']
        filename = secure_filename(file.filename)
        save_path = os.path.join(upload_path, component.name)
        if not os.path.exists(save_path):
            os.makedirs(save_path)
        file.save(os.path.join(upload_path, component.name, filename))
        upload_file = UploadFile(name=filename,
                                 path=component.name,
                                 type=type,
                                 component_id=component.id
                                 )
        db.session.add(upload_file)


def _render(content, kwargs={}):
    if not kwargs.has_key('title_name'):
        kwargs.update(title_name=u'组件')
    html = "component/%s.html" % content
    return render_template(html, **kwargs)

app/templates/component/_js.html
<script>
    $(function () {
        // 名称校验
        $('#name').addClass('valid_letter_num');
        $('#name').attr('maxlength', 30);
        {#        $('#name').addClass('CommonNameCN');#}
        {#        $('#name').attr('min', 1);#}
        {#        $('#name').attr('max', 15);#}
        // 版本
        $('#version').attr('maxlength', 30);
        // 适用系统
        $('#os').addClass('valid_os');
        $('#os').attr('maxlength', 30);
        // 脚本内容
        $('#content').attr({'rows': 15});
        $('#content').ace({theme: 'xcode', lang: 'yaml'});


        // 安装包/脚本上传
        $('#files').attr({name: 'files[]', multiple: true});
        {#        $('#files').addClass('file-loading');#}
        {#        , uploadUrl: "/upload/file"#}
        $('#files').fileinput({
{#            initialPreview: [#}
{#                'http://127.0.0.1:5000/uploads/ntp_server/ntp_server.conf',#}
{#                'http://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/631px-FullMoon2010.jpg',#}
{#                'http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_Eastern_Hemisphere.jpg/600px-Earth_Eastern_Hemisphere.jpg'#}
{#            ],#}
{#            initialPreviewAsData: true,#}
            // 隐藏Upload按钮
            showUpload: false,
            // 是否显示文件信息
            {#            showPreview: false,#}
            {#            maxFilePreviewSize: 1024,#}
            maxFileSize: 16 * 1024 * 1024,
            // 上传文件个数
            maxFileCount: 10
        });

        // 配置/模版上传
        $('#templates').attr({name: 'templates[]', multiple: true});
        $('#templates').fileinput({showUpload: false});

        // 备注
        $('#notes').attr({'rows': 5});

        // $("#input-44").fileinput({
        // 实现可拖动
        // theme: "fa",
        // uploadUrl: "/file-upload-batch/2",

        // hide image, pdf, text or other content in the thumbnail preview
        // hideThumbnailContent: true,

        // maxFilePreviewSize: 10240
        // 上传文件个数
        // maxFileCount: 10,
        // 允许的类型
        // allowedFileTypes: ["image", "video"]
        // 允许的后缀
        // allowedFileExtensions: ["jpg", "png", "gif"]
        //         });


    });

    $("form").validate({ignore: []});

    // 变量增加行
    function add_var_row() {
        var tbody = $('#var_table tbody');
        count = tbody.children('tr').length;
        $.ajax({
            url: '/component/ajax_add_var_tr/' + count,
            method: "get",
            success: function (response) {
                tbody.children('tr:last').before(response);
            }
        });
    }

    // 变量删除最后行
    function del_var_row() {
        $('#var_table tbody tr:nth-last-child(2)').remove();
    }
</script>

app/templates/component/_var_tr.html
<tr>
    <td>{{ i }}</td>
    <td>
        <input class="form-control" id="var_name_{{ i }}" name="var_name[]" type="text"
               value="">
    </td>
    <td>
        <input class="form-control" id="var_value_{{ i }}" name="var_value[]" type="text"
               value="">
    </td>
    <td>
        <label class="radio-inline">
            <input type="radio" name="var_type_{{ i }}" id="var_type_default_{{ i }}" value="default"
                   checked="">默认
        </label>
        <label class="radio-inline">
            <input type="radio" name="var_type_{{ i }}" id="var_type_dynamic_{{ i }}"
                   value="dynamic">动态
        </label>
    </td>
</tr>

app/templates/component/edit.html
{% extends "extends/base_page.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
    <form action="" id="myform" method="post" class="form form-horizontal" enctype="multipart/form-data" role="form"
          novalidate="novalidate">
        {{ form.csrf_token }}
        {% import 'macros/render_field.html' as macros %}
        {{ macros.render_field(form.name) }}
        {{ macros.render_field(form.type) }}
        {{ macros.render_field(form.version) }}
        {{ macros.render_field(form.os) }}
        {{ macros.render_field(form.content) }}
        {% include 'component/../includes/_field_var.html' %}
        {{ macros.render_field(form.files) }}
        {{ macros.render_field(form.templates) }}
        {{ macros.render_field(form.notes) }}

        {% import 'macros/render_submit.html' as macros %}
        {{ macros.render_submit(url_for('component.index')) }}
    </form>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% include 'component/_js.html' %}
{% endblock %}

app/templates/component/file_index.html
{% include 'upload_file/index.html' %}

app/templates/component/form.html
{% extends "extends/base_page.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
    {#    {{ wtf.quick_form(form, id="myform", form_type="horizontal", horizontal_columns=('sm', 2, 6)) }}#}
    <form action="" id="myform" method="post" class="form form-horizontal" enctype="multipart/form-data" role="form"
          novalidate="novalidate">
        {{ form.csrf_token }}
        {% import 'macros/render_field.html' as macros %}
        {{ macros.render_field(form.name) }}
        {{ macros.render_field(form.type) }}
        {{ macros.render_field(form.version) }}
        {{ macros.render_field(form.os) }}
        {{ macros.render_field(form.content) }}
        {% if "new" in request.url_rule.rule %}
            {% include 'includes/_field_var.html' %}
            {{ macros.render_field(form.files) }}
            {{ macros.render_field(form.templates) }}
        {% endif %}
        {{ macros.render_field(form.notes) }}

        {% import 'macros/render_submit.html' as macros %}
        {{ macros.render_submit(url_for('component.index')) }}
    </form>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% include 'component/_js.html' %}
{% endblock %}

app/templates/component/form_bk.html
{% extends "extends/base_page.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_header %}
    <div class="page-header">
        <h3>{{ page_header }}</h3>
    </div>
{% endblock %}
{% block page_content %}
    {{ wtf.quick_form(form, id="myform", form_type="horizontal", horizontal_columns=('sm', 2, 6)) }}
    {#    <label class="control-label">Select File</label>#}
    {#<input id="input-4" name="input4[]" type="file" multiple class="file-loading">#}
    {#    <form method=post enctype=multipart/form-data>#}
    {#        <p><input type=file name=file>#}
    {#            <input type=submit value=Upload>#}
    {#    </form>#}
    {#    <div class="form-group">#}
    {#        <label class="control-label col-sm-2" for="name">主机</label>#}
    {#        <div class=" col-sm-6">#}
    {#            <input type=file name=file class="form-control">#}
    {#            <input type=submit value=Upload>#}
    {#            <input class="form-control CommonNameCN" id="name" name="name" required="" type="text" value=""#}
    {#                   aria-required="true">#}
    {#        </div>#}
    {#    </div>#}
    <form id="fileupload" action="//jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">
        {#    <noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>#}
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="form-group">
            <label class="control-label col-sm-2" for="name">上传</label>
            <div class=" col-sm-6">
                <div class="row fileupload-buttonbar">
                    <div class="col-lg-7">
                        <!-- The fileinput-button span is used to style the file input field as button -->
                        <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="file" multiple>
                </span>
                        <button type="submit" class="btn btn-primary start">
                            <i class="glyphicon glyphicon-upload"></i>
                            <span>Start upload</span>
                        </button>
                        <button type="reset" class="btn btn-warning cancel">
                            <i class="glyphicon glyphicon-ban-circle"></i>
                            <span>Cancel upload</span>
                        </button>
                        <button type="button" class="btn btn-danger delete">
                            <i class="glyphicon glyphicon-trash"></i>
                            <span>Delete</span>
                        </button>
                        <input type="checkbox" class="toggle">
                        <!-- The global file processing state -->
                        <span class="fileupload-process"></span>
                    </div>
                    <!-- The global progress state -->
                    <div class="col-lg-5 fileupload-progress fade">
                        <!-- The global progress bar -->
                        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0"
                             aria-valuemax="100">
                            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                        </div>
                        <!-- The extended global progress state -->
                        <div class="progress-extended">&nbsp;</div>
                    </div>
                </div>
                <!-- The table listing the files available for upload/download -->
                <table role="presentation" class="table table-striped">
                    <tbody class="files"></tbody>
                </table>
    </form>

    {% raw %}
    <!-- The template to display files available for upload -->
    <script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}


    </script>
    <!-- The template to display files available for download -->
    <script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}


    </script>
    {% endraw %}


{% endblock %}

{% block scripts %}
    {{ super() }}
    {% include 'component/_js.html' %}
    {#    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>#}

    <!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
    {#    <script src="static/js/vendor/jquery.ui.widget.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/vendor/jquery.ui.widget.js') }}"></script>


    <!-- The Templates plugin is included to render the upload/download listings -->
    <script src="http://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>

    <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
    <script src="http://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>

    <!-- The Canvas to Blob plugin is included for image resizing functionality -->
    <script src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>

    <!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
    <!-- <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script> -->
    <!-- blueimp Gallery script -->
    <script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    <!-- The Iframe Transport is required for browsers without support for XHR file uploads -->

    {#    <script src="static/js/jquery.iframe-transport.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/jquery.iframe-transport.js') }}"></script>


    <!-- The basic File Upload plugin -->
    {#    <script src="static/js/jquery.fileupload.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/jquery.fileupload.js') }}"></script>


    <!-- The File Upload processing plugin -->
    {#    <script src="static/js/jquery.fileupload-process.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/jquery.fileupload-process.js') }}"></script>


    <!-- The File Upload image preview & resize plugin -->
    {#    <script src="static/js/jquery.fileupload-image.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/jquery.fileupload-image.js') }}"></script>


    <!-- The File Upload audio preview plugin -->
    {#    <script src="static/js/jquery.fileupload-audio.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/jquery.fileupload-audio.js') }}"></script>


    <!-- The File Upload video preview plugin -->
    {#    <script src="static/js/jquery.fileupload-video.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/jquery.fileupload-video.js') }}"></script>


    <!-- The File Upload validation plugin -->
    {#    <script src="static/js/jquery.fileupload-validate.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/jquery.fileupload-validate.js') }}"></script>


    <!-- The File Upload user interface plugin -->
    {#    <script src="static/js/jquery.fileupload-ui.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/jquery.fileupload-ui.js') }}"></script>


    <!-- The main application script -->
    {#    <script src="static/js/main.js"></script>#}
    <script src="{{ url_for('static', filename='upload/js/main.js') }}"></script>

    <!-- The XDomainRequest Transport is included for cross-domain file deletion for IE 8 and IE 9 -->
    <!--[if (gte IE 8)&(lt IE 10)]>
    <script src="js/cors/jquery.xdr-transport.js"></script>
    <![endif]-->

{% endblock %}

app/templates/component/index.html
{% extends "extends/base_table.html" %}
{% block table_content %}
    {% import 'macros/render_btn.html' as macros %}
    <div class="dataTable_wrapper">
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
            <tr>
                <th width="10%">名称</th>
                <th width="10%">类型</th>
                <th width="10%">版本</th>
                <th width="10%">适用于</th>
                <th width="10%">变量</th>
                <th width="10%">文件</th>
                <th width="20%">备注</th>
                <th width="20%">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in objects %}
                <tr>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.type }}</td>
                    <td>{{ obj.version }}</td>
                    <td>{{ obj.os }}</td>
                    <td>
                        <a href="{{ url_for('.variable_index', id=obj.id) }}">
                            变量: {{ obj.variables.count() }}
                        </a>
                    </td>
                    <td>
                        <a href="{{ url_for('.file_index', id=obj.id) }}">
                            文件: {{ obj.upload_files.count() }}
                        </a>
                    </td>
                    <td>{{ obj.notes }}</td>
                    <td>
                        {{ macros.render_edit_btn('component.edit', obj.id) }}
                        {#                        {{ macros.render_btn('变量', 'component.edit', obj.id) }}#}
                        {#                        {{ macros.render_btn('文件', 'component.edit', obj.id) }}#}
                        {{ macros.render_del_btn('component.delete', obj.id) }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.table-responsive -->
    {{ macros.render_add_btn('component.new') }}
{% endblock %}

app/templates/component/new.html
{% extends "extends/base_page.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
    {{ request.url }}
    <form action="" id="myform" method="post" class="form form-horizontal" enctype="multipart/form-data" role="form"
          novalidate="novalidate">
        {{ form.csrf_token }}
        {% import 'macros/render_field.html' as macros %}
        {{ macros.render_field(form.name) }}
        {{ macros.render_field(form.type) }}
        {{ macros.render_field(form.version) }}
        {{ macros.render_field(form.os) }}
        {{ macros.render_field(form.content) }}
        {% include 'includes/_field_var.html' %}
        {{ macros.render_field(form.files) }}
        {{ macros.render_field(form.templates) }}
        {{ macros.render_field(form.notes) }}

        {% import 'macros/render_submit.html' as macros %}
        {{ macros.render_submit(url_for('component.index')) }}
    </form>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% include 'component/_js.html' %}
{% endblock %}

app/templates/component/variable_index.html
{% include 'variable/index.html' %}